version: 2
ethernets:
    eth0:
        match:
            macaddress: '00:8b:cd:34:21:97'
        addresses:
            - 161.248.63.8/24
            - '2401:e4e0:100:8::a/64'
        gateway4: 161.248.63.1
        gateway6: '2401:e4e0:100::1'
        nameservers:
            addresses:
                - 161.248.63.63
                - 1.1.1.1
                - '2001:4860:4860::8888'
                - '2001:4860:4860::8844'