name: "Init x86_64 DD"
on:
  workflow_dispatch:
    inputs:
      ip:
        description: 'Ip or Domain'
        type: string
        required: true
      flakeAttr:
        description: 'OS Config Hostname'
        type: string
        default: 'bios-init-tmp'
        required: true
      disk:
        description: "Disk"
        type: choice
        required: true
        options:
          - vda
          - sda

env:
  SSH: ssh -o StrictHostKeyChecking=no
  HOST: root@${{ inputs.ip }}

jobs:

  takeover:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir -m 0755  ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - run: wget https://dd.mlyxshi.com/alpine-takeover-rootfs.tar.gz

    - name: Set up WARP (IPv6 only)
      if: contains(inputs.ip, ':')
      uses: fscarmen/warp-on-actions@v1.4
      with:
        stack: dual
        mode: client    

    - run: |
        until $SSH -o ConnectTimeout=10 $HOST
        do
          echo "Server Not Reachable, Waiting..."
          sleep 5
        done

    - run: scp -o StrictHostKeyChecking=no alpine-takeover-rootfs.tar.gz root@[${{ inputs.ip }}]:/root/
      if: contains(inputs.ip, ':')

    - run: scp -o StrictHostKeyChecking=no alpine-takeover-rootfs.tar.gz $HOST:/root/
      if: ${{ !contains(inputs.ip, ':') }}

    - run: $SSH $HOST 'mkdir -p /takeover' 
    - run: $SSH $HOST 'mount -t tmpfs tmpfs /takeover' 

    - run: $SSH $HOST 'tar -xvf alpine-takeover-rootfs.tar.gz -C /takeover'
    - run: $SSH $HOST 'sh /takeover/takeover-non-interactive.sh'

  build-dd:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir -m 0755  ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

        cat > ~/.ssh/ssh_config <<EOF
        Host github.com
          User git
          IdentityFile ~/.ssh/id_ed25519
        EOF

    - uses: actions/checkout@master
    - uses: DeterminateSystems/nix-installer-action@main

    - run: |
        outPath=$(nix build --no-link --print-out-paths .#nixosConfigurations.${{ inputs.flakeAttr }}.config.system.build.raw)
        echo "outPath=$outPath" >> "$GITHUB_ENV"

    - name: Set up WARP (IPv6 only)
      if: contains(inputs.ip, ':')
      uses: fscarmen/warp-on-actions@v1.4
      with:
        stack: dual
        mode: client    

    - run: |
        until $SSH -p 80 -o ConnectTimeout=10 $HOST
        do
          echo "TakeOver Environment Not Reachable, Waiting..."
          sleep 5
        done

    - run: cat $outPath/${{ inputs.flakeAttr }}.img | $SSH -p 80  $HOST "dd of=/dev/${{ inputs.disk }}"
    - run: curl "https://api.day.app/${{ secrets.BARK_KEY }}/NixOS%20Install%20Done/${{ inputs.flakeAttr }}?group=NixOS&icon=https://hydra.nixos.org/logo"

    - name: Force reboot
      continue-on-error: true 
      run: $SSH -p 80 ServerAliveInterval=5 -o ServerAliveCountMax=2 $HOST reboot -f