name: "Kexec Release"
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  aarch64:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@master
    - uses: DeterminateSystems/nix-installer-action@main
    
    - run: |
        kernelOutPath=$(nix build --no-link --print-out-paths .#nixosConfigurations.kexec-aarch64.config.system.build.kernel)
        initrdOutPath=$(nix build --no-link --print-out-paths .#nixosConfigurations.kexec-aarch64.config.system.build.initialRamdisk)
        kexecOutPath=$(nix build --no-link --print-out-paths nixpkgs#pkgsStatic.kexec-tools)
        
        ln -sf $kernelOutPath/Image /tmp/kernel

        gh release upload aarch64 /tmp/kernel --clobber
        gh release upload aarch64 $initrdOutPath/initrd --clobber
        gh release upload aarch64 $kexecOutPath/bin/kexec --clobber


  x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: DeterminateSystems/nix-installer-action@main
    
    - run: |
        kernelOutPath=$(nix build --no-link --print-out-paths .#nixosConfigurations.kexec-x86_64.config.system.build.kernel)
        initrdOutPath=$(nix build --no-link --print-out-paths .#nixosConfigurations.kexec-x86_64.config.system.build.initialRamdisk)
        initrdOutPath2=$(nix build --no-link --print-out-paths .#nixosConfigurations.kexec-x86_64-tmp.config.system.build.initialRamdisk)
        kexecOutPath=$(nix build --no-link --print-out-paths nixpkgs#pkgsStatic.kexec-tools)

        ln -sf $kernelOutPath/bzImage /tmp/kernel
        ln -sf $initrdOutPath2/initrd /tmp/initrd-tmp
        
        gh release upload x86_64 /tmp/kernel --clobber
        gh release upload x86_64 /tmp/initrd-tmp --clobber
        gh release upload x86_64 $initrdOutPath/initrd --clobber
        gh release upload x86_64 $kexecOutPath/bin/kexec --clobber