name: "System Upgrade DMIT"
on:
  # push:
  #   paths: 
  #     - 'flake.lock'
  workflow_dispatch:

jobs:
  Update:
    runs-on: ubuntu-latest  
    strategy:
      fail-fast: false
      matrix:
        host: [nrt] 
    steps:
    - uses: actions/checkout@master
    - uses: DeterminateSystems/nix-installer-action@main
    - run: |
        mkdir -m 0755  ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

        cat > ~/.ssh/config <<EOF
        Host ${{ matrix.host }}
          HostName ${{ matrix.host }}.mlyxshi.com
          HostKeyAlias ${{ matrix.host }}
          User root
          Port 23333
          StrictHostKeyChecking no
        EOF
        
    - name: Build and Deploy
      uses: ./.github/actions/system-upgrade
