name: "Upload dd image to R2"
on:
  workflow_dispatch:

env:
  CLOUDFLARE_R2_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
  CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
  CLOUDFLARE_R2_ENDPOINT: ${{ secrets.CLOUDFLARE_R2_ENDPOINT }}

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: DeterminateSystems/nix-installer-action@main

    - name: Configure
      run: |
        sudo apt install -y rclone
        mkdir -p ~/.config/rclone
        cat <<EOF > ~/.config/rclone/rclone.conf
        [r2]
        type = s3
        provider = Cloudflare
        access_key_id = ${CLOUDFLARE_R2_ACCESS_KEY_ID}
        secret_access_key = ${CLOUDFLARE_R2_SECRET_ACCESS_KEY}
        endpoint = ${CLOUDFLARE_R2_ENDPOINT}
        EOF
    
    - name: Build vda
      run: |
        outPath1=$(nix build --no-link --print-out-paths .#nixosConfigurations.bios-init-vda.config.system.build.raw)
        echo "outPath1=$outPath1" >> "$GITHUB_ENV"
  
    - name: Build sda
      run: |
        outPath2=$(nix build --no-link --print-out-paths .#nixosConfigurations.bios-init-sda.config.system.build.raw)
        echo "outPath2=$outPath2" >> "$GITHUB_ENV"

    - name: Upload vda
      run: |
        rclone copy $outPath1/bios-init-vda.img r2:ddraw

    - name: Upload sda
      run: |
        rclone copy $outPath2/bios-init-sda.img r2:ddraw