name: "Upload dd image to R2"
on:
  workflow_dispatch:

env:
  CLOUDFLARE_R2_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
  CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
  CLOUDFLARE_R2_ENDPOINT: ${{ secrets.CLOUDFLARE_R2_ENDPOINT }}

jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # host: [bios-init-vda,bios-init-sda]
        host: [bios-init-test]
    steps:
    - uses: actions/checkout@master
    - uses: DeterminateSystems/nix-installer-action@main

    - name: Configure
      run: |
        sudo apt install -y rclone
        mkdir -p ~/.config/rclone
        cat <<EOF > ~/.config/rclone/rclone.conf
        [r2]
        type = s3
        provider = Cloudflare
        access_key_id = ${CLOUDFLARE_R2_ACCESS_KEY_ID}
        secret_access_key = ${CLOUDFLARE_R2_SECRET_ACCESS_KEY}
        endpoint = ${CLOUDFLARE_R2_ENDPOINT}
        EOF
    
    - name: Build
      run: |
        outPath=$(nix build --no-link --print-out-paths .#nixosConfigurations.${{ matrix.host }}.config.system.build.raw)
        echo "outPath=$outPath" >> "$GITHUB_ENV"

    - name: Upload
      run: |
        rclone copy $outPath/${{ matrix.host }}.img r2:ddraw
